services:
  - type: web
    name: cardio-frontend-v2   # <-- new name
    rootDir: frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist -l $PORT
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: VITE_API_BASE
        sync: false

  - type: web
    name: cardio-backend-v2    # <-- new name
    rootDir: backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: ADMIN_PASSWORD
        sync: false
