services:
  - type: web
    name: cardio-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: ADMIN_PASSWORD
        sync: false
  
  - type: web
    name: cardio-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticpublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: VITE_API_BASE
        sync: false
        
